name: bankingapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
   sdk: flutter


  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  nfc_manager: ^3.5.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  go_router: ^14.6.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  zoom_tap_animation: ^1.1.0
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  google_ml_kit: ^0.19.0
  equatable: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Golds
      fonts:
        - asset: assets/fonts/GolosText-Black.ttf
          weight: 900
        - asset: assets/fonts/GolosText-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/GolosText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GolosText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GolosText-Medium.ttf
          weight: 500
        - asset: assets/fonts/GolosText-Regular.ttf
          weight: 400